# Generated by Django 5.2.9 on 2025-12-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Upload'), ('manual', 'Manual Input')], max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='assessments/')),
                ('raw_extracted_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
            ],
        ),
    ]
