# Generated by Django 5.2.9 on 2025-12-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='assessments/doc'),
        ),
    ]
