# Generated by Django 6.0 on 2026-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
