# Generated by Django 6.0 on 2026-01-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='pdf_file',
            new_name='document_file',
        ),
    ]
