# Generated by Django 5.2.9 on 2025-12-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('master_super_admin', 'Master Super Admin'), ('super_admin', 'Super Admin'), ('client_admin', 'Client admin'), ('nurse', 'Nurse')], max_length=20),
        ),
    ]
