# Generated by Django 6.0 on 2026-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='careplans/'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
